import type { NotificationCategory, NotificationChannel, NotificationPriority } from "./types";

export interface NotificationEventDefinition {
  key: string;
  label: string;
  description: string;
  category: NotificationCategory;
  defaultTitle: string;
  defaultMessage: (payload: Record<string, unknown>) => string;
  defaultPriority: NotificationPriority;
  availableChannels: readonly NotificationChannel[];
  defaults: Readonly<Record<NotificationChannel, boolean>>;
  allowedRecipientRoles: readonly string[];
  requiredSection: string | null;
  navigationTarget: (payload: Record<string, unknown>) => string;
  dedupeStrategy: "source_event" | "entity" | "entity_window" | "failure_window";
  rateLimitStrategy: "standard" | "failure_cooldown" | "critical_bypass";
  cooldownSeconds: number;
  canBypassQuietHours: boolean;
  soundAllowed: boolean;
  sensitivePreviewAllowed: boolean;
}

const roles = {
  managers: ["owner", "supervisor", "admin", "manager"],
  operators: ["owner", "supervisor", "admin", "manager", "agent"],
  everyone: ["owner", "supervisor", "admin", "manager", "agent", "viewer"],
} as const;

const value = (payload: Record<string, unknown>, key: string, fallback: string) => {
  const candidate = payload[key];
  return typeof candidate === "string" && candidate.trim() ? candidate.trim() : fallback;
};
const entityUrl = (base: string) => (payload: Record<string, unknown>) => {
  const id = value(payload, "entity_id", "");
  return id ? `${base}?id=${encodeURIComponent(id)}` : base;
};

function event(
  definition: Omit<NotificationEventDefinition, "defaults" | "rateLimitStrategy"> & {
    defaults?: Partial<Record<NotificationChannel, boolean>>;
    rateLimitStrategy?: NotificationEventDefinition["rateLimitStrategy"];
  },
): NotificationEventDefinition {
  return {
    ...definition,
    defaults: { in_app: true, push: false, sound: false, ...definition.defaults },
    rateLimitStrategy: definition.rateLimitStrategy ?? (
      definition.defaultPriority === "critical" ? "critical_bypass" :
      definition.dedupeStrategy === "failure_window" ? "failure_cooldown" : "standard"
    ),
  };
}

export const NOTIFICATION_EVENTS = {
  "order.created": event({ key: "order.created", label: "New order", description: "A new COD order enters the workspace.", category: "orders", defaultTitle: "New order", defaultMessage: (p) => `Order ${value(p,"order_number","")} is ready for confirmation.`, defaultPriority: "normal", availableChannels: ["in_app","push","sound"], defaults: { push: true, sound: true }, allowedRecipientRoles: roles.managers, requiredSection: "Orders", navigationTarget: entityUrl("/orders"), dedupeStrategy: "source_event", cooldownSeconds: 0, canBypassQuietHours: false, soundAllowed: true, sensitivePreviewAllowed: true }),
  "order.assigned": event({ key: "order.assigned", label: "Order assigned", description: "An order is assigned to the current agent.", category: "confirmation", defaultTitle: "Order assigned", defaultMessage: (p) => `Order ${value(p,"order_number","")} was assigned to you.`, defaultPriority: "high", availableChannels: ["in_app","push","sound"], defaults: { push: true, sound: true }, allowedRecipientRoles: roles.operators, requiredSection: "Confirmation", navigationTarget: entityUrl("/confirmation"), dedupeStrategy: "source_event", cooldownSeconds: 0, canBypassQuietHours: false, soundAllowed: true, sensitivePreviewAllowed: true }),
  "order.unassigned": event({ key: "order.unassigned", label: "Order unassigned", description: "An order is removed from an agent queue.", category: "confirmation", defaultTitle: "Order unassigned", defaultMessage: () => "An order assignment changed.", defaultPriority: "normal", availableChannels: ["in_app","push"], allowedRecipientRoles: roles.operators, requiredSection: "Confirmation", navigationTarget: entityUrl("/confirmation"), dedupeStrategy: "source_event", cooldownSeconds: 0, canBypassQuietHours: false, soundAllowed: false, sensitivePreviewAllowed: false }),
  "order.confirmed": event({ key: "order.confirmed", label: "Order confirmed", description: "A COD order is confirmed.", category: "confirmation", defaultTitle: "Order confirmed", defaultMessage: (p) => `Order ${value(p,"order_number","")} was confirmed.`, defaultPriority: "normal", availableChannels: ["in_app","push"], allowedRecipientRoles: roles.operators, requiredSection: "Confirmation", navigationTarget: entityUrl("/orders"), dedupeStrategy: "source_event", cooldownSeconds: 0, canBypassQuietHours: false, soundAllowed: true, sensitivePreviewAllowed: true }),
  "order.no_response": event({ key: "order.no_response", label: "Customer follow-up", description: "An assigned order needs another confirmation attempt.", category: "confirmation", defaultTitle: "Customer needs follow-up", defaultMessage: () => "An assigned order needs another confirmation attempt.", defaultPriority: "high", availableChannels: ["in_app","push","sound"], defaults: { push: true, sound: true }, allowedRecipientRoles: roles.operators, requiredSection: "Confirmation", navigationTarget: entityUrl("/confirmation"), dedupeStrategy: "source_event", cooldownSeconds: 0, canBypassQuietHours: false, soundAllowed: true, sensitivePreviewAllowed: true }),
  "order.cancelled": event({ key: "order.cancelled", label: "Order cancelled", description: "A COD order is cancelled.", category: "orders", defaultTitle: "Order cancelled", defaultMessage: () => "An order was cancelled.", defaultPriority: "normal", availableChannels: ["in_app","push"], allowedRecipientRoles: roles.operators, requiredSection: "Orders", navigationTarget: entityUrl("/orders"), dedupeStrategy: "source_event", cooldownSeconds: 0, canBypassQuietHours: false, soundAllowed: true, sensitivePreviewAllowed: true }),
  "order.duplicate": event({ key: "order.duplicate", label: "Duplicate order", description: "A suspected duplicate order is detected.", category: "orders", defaultTitle: "Duplicate order detected", defaultMessage: () => "Review a suspected duplicate order.", defaultPriority: "high", availableChannels: ["in_app","push"], defaults: { push: true }, allowedRecipientRoles: roles.operators, requiredSection: "Orders", navigationTarget: entityUrl("/orders"), dedupeStrategy: "source_event", cooldownSeconds: 0, canBypassQuietHours: false, soundAllowed: true, sensitivePreviewAllowed: true }),
  "order.blacklisted": event({ key: "order.blacklisted", label: "Blacklisted order", description: "An order is marked as blacklisted.", category: "orders", defaultTitle: "Blacklisted order", defaultMessage: () => "A blacklisted order needs review.", defaultPriority: "high", availableChannels: ["in_app","push"], defaults: { push: true }, allowedRecipientRoles: roles.operators, requiredSection: "Orders", navigationTarget: entityUrl("/orders"), dedupeStrategy: "source_event", cooldownSeconds: 0, canBypassQuietHours: false, soundAllowed: true, sensitivePreviewAllowed: false }),
  "shipping.ready_to_send": event({ key: "shipping.ready_to_send", label: "Ready to send", description: "A confirmed order is ready for a carrier.", category: "shipping", defaultTitle: "Order ready to send", defaultMessage: () => "A confirmed order is ready for shipping.", defaultPriority: "normal", availableChannels: ["in_app","push"], allowedRecipientRoles: roles.managers, requiredSection: "Shipping", navigationTarget: entityUrl("/shipping"), dedupeStrategy: "source_event", cooldownSeconds: 0, canBypassQuietHours: false, soundAllowed: true, sensitivePreviewAllowed: true }),
  "shipping.sent_to_carrier": event({ key: "shipping.sent_to_carrier", label: "Sent to carrier", description: "A parcel is registered with a carrier.", category: "shipping", defaultTitle: "Sent to carrier", defaultMessage: () => "An order was sent to its carrier.", defaultPriority: "normal", availableChannels: ["in_app","push"], allowedRecipientRoles: roles.managers, requiredSection: "Shipping", navigationTarget: entityUrl("/delivering"), dedupeStrategy: "source_event", cooldownSeconds: 0, canBypassQuietHours: false, soundAllowed: true, sensitivePreviewAllowed: true }),
  "shipping.picked_up": event({ key: "shipping.picked_up", label: "Picked up", description: "The carrier picked up a parcel.", category: "shipping", defaultTitle: "Shipment picked up", defaultMessage: () => "A carrier picked up a shipment.", defaultPriority: "normal", availableChannels: ["in_app","push"], allowedRecipientRoles: roles.managers, requiredSection: "Shipping", navigationTarget: entityUrl("/delivering"), dedupeStrategy: "source_event", cooldownSeconds: 0, canBypassQuietHours: false, soundAllowed: true, sensitivePreviewAllowed: true }),
  "shipping.in_transit": event({ key: "shipping.in_transit", label: "In transit", description: "A shipment is moving through the carrier network.", category: "shipping", defaultTitle: "Shipment in transit", defaultMessage: () => "A shipment is in transit.", defaultPriority: "normal", availableChannels: ["in_app","push"], allowedRecipientRoles: roles.managers, requiredSection: "Shipping", navigationTarget: entityUrl("/delivering"), dedupeStrategy: "source_event", cooldownSeconds: 0, canBypassQuietHours: false, soundAllowed: true, sensitivePreviewAllowed: true }),
  "shipping.out_for_delivery": event({ key: "shipping.out_for_delivery", label: "Out for delivery", description: "A parcel is with the delivery agent.", category: "shipping", defaultTitle: "Out for delivery", defaultMessage: () => "A shipment is out for delivery.", defaultPriority: "high", availableChannels: ["in_app","push","sound"], defaults: { push: true }, allowedRecipientRoles: roles.managers, requiredSection: "Shipping", navigationTarget: entityUrl("/delivering"), dedupeStrategy: "source_event", cooldownSeconds: 0, canBypassQuietHours: false, soundAllowed: true, sensitivePreviewAllowed: true }),
  "shipping.delivered": event({ key: "shipping.delivered", label: "Delivered", description: "A COD shipment is delivered.", category: "shipping", defaultTitle: "Order delivered", defaultMessage: () => "A shipment was delivered.", defaultPriority: "normal", availableChannels: ["in_app","push"], defaults: { push: true }, allowedRecipientRoles: roles.managers, requiredSection: "Shipping", navigationTarget: entityUrl("/delivering"), dedupeStrategy: "source_event", cooldownSeconds: 0, canBypassQuietHours: false, soundAllowed: true, sensitivePreviewAllowed: true }),
  "shipping.refused": event({ key: "shipping.refused", label: "Delivery refused", description: "A customer refuses a COD delivery.", category: "shipping", defaultTitle: "Delivery refused", defaultMessage: () => "A delivery was refused.", defaultPriority: "high", availableChannels: ["in_app","push","sound"], defaults: { push: true, sound: true }, allowedRecipientRoles: roles.managers, requiredSection: "Shipping", navigationTarget: entityUrl("/delivering"), dedupeStrategy: "source_event", cooldownSeconds: 0, canBypassQuietHours: false, soundAllowed: true, sensitivePreviewAllowed: true }),
  "shipping.returned": event({ key: "shipping.returned", label: "Shipment returned", description: "A shipment is returned to the seller.", category: "shipping", defaultTitle: "Shipment returned", defaultMessage: () => "A shipment was returned.", defaultPriority: "high", availableChannels: ["in_app","push","sound"], defaults: { push: true, sound: true }, allowedRecipientRoles: roles.managers, requiredSection: "Shipping", navigationTarget: entityUrl("/delivering"), dedupeStrategy: "source_event", cooldownSeconds: 0, canBypassQuietHours: false, soundAllowed: true, sensitivePreviewAllowed: true }),
  "shipping.cancelled": event({ key: "shipping.cancelled", label: "Shipment cancelled", description: "A carrier shipment is cancelled.", category: "shipping", defaultTitle: "Shipment cancelled", defaultMessage: () => "A shipment was cancelled.", defaultPriority: "high", availableChannels: ["in_app","push"], defaults: { push: true }, allowedRecipientRoles: roles.managers, requiredSection: "Shipping", navigationTarget: entityUrl("/delivering"), dedupeStrategy: "source_event", cooldownSeconds: 0, canBypassQuietHours: false, soundAllowed: true, sensitivePreviewAllowed: true }),
  "shipping.provider_error": event({ key: "shipping.provider_error", label: "Carrier error", description: "A shipping provider operation fails.", category: "shipping", defaultTitle: "Carrier error", defaultMessage: () => "A shipping provider needs attention.", defaultPriority: "high", availableChannels: ["in_app","push","sound"], defaults: { push: true, sound: true }, allowedRecipientRoles: roles.managers, requiredSection: "Shipping", navigationTarget: () => "/settings?tab=integrations", dedupeStrategy: "failure_window", cooldownSeconds: 900, canBypassQuietHours: false, soundAllowed: true, sensitivePreviewAllowed: false }),
  "shipping.tracking_failed": event({ key: "shipping.tracking_failed", label: "Tracking failed", description: "A tracking refresh fails.", category: "shipping", defaultTitle: "Tracking sync failed", defaultMessage: () => "Shipment tracking could not be refreshed.", defaultPriority: "high", availableChannels: ["in_app","push"], defaults: { push: true }, allowedRecipientRoles: roles.managers, requiredSection: "Shipping", navigationTarget: () => "/shipping", dedupeStrategy: "failure_window", cooldownSeconds: 900, canBypassQuietHours: false, soundAllowed: true, sensitivePreviewAllowed: false }),
  "inventory.low_stock": event({ key: "inventory.low_stock", label: "Low stock", description: "Tracked stock reaches its warning quantity.", category: "inventory", defaultTitle: "Low stock", defaultMessage: (p) => `${value(p,"product_name","A product")} is running low.`, defaultPriority: "high", availableChannels: ["in_app","push","sound"], defaults: { push: true, sound: true }, allowedRecipientRoles: roles.managers, requiredSection: "Inventory", navigationTarget: entityUrl("/products-inventory"), dedupeStrategy: "entity_window", cooldownSeconds: 3600, canBypassQuietHours: false, soundAllowed: true, sensitivePreviewAllowed: true }),
  "inventory.out_of_stock": event({ key: "inventory.out_of_stock", label: "Out of stock", description: "Tracked stock reaches zero.", category: "inventory", defaultTitle: "Out of stock", defaultMessage: (p) => `${value(p,"product_name","A product")} is out of stock.`, defaultPriority: "critical", availableChannels: ["in_app","push","sound"], defaults: { push: true, sound: true }, allowedRecipientRoles: roles.managers, requiredSection: "Inventory", navigationTarget: entityUrl("/products-inventory"), dedupeStrategy: "entity_window", cooldownSeconds: 3600, canBypassQuietHours: true, soundAllowed: true, sensitivePreviewAllowed: true }),
  "inventory.restocked": event({ key: "inventory.restocked", label: "Restocked", description: "A tracked product returns above its warning level.", category: "inventory", defaultTitle: "Product restocked", defaultMessage: () => "A product is back in stock.", defaultPriority: "normal", availableChannels: ["in_app","push"], allowedRecipientRoles: roles.managers, requiredSection: "Inventory", navigationTarget: entityUrl("/products-inventory"), dedupeStrategy: "source_event", cooldownSeconds: 0, canBypassQuietHours: false, soundAllowed: true, sensitivePreviewAllowed: true }),
  "inventory.adjusted": event({ key: "inventory.adjusted", label: "Inventory adjusted", description: "A manual inventory adjustment is recorded.", category: "inventory", defaultTitle: "Inventory adjusted", defaultMessage: () => "Inventory quantities were adjusted.", defaultPriority: "normal", availableChannels: ["in_app"], allowedRecipientRoles: roles.managers, requiredSection: "Inventory", navigationTarget: entityUrl("/products-inventory"), dedupeStrategy: "source_event", cooldownSeconds: 0, canBypassQuietHours: false, soundAllowed: false, sensitivePreviewAllowed: true }),
  "team.invitation_received": event({ key: "team.invitation_received", label: "Workspace invitation", description: "A user receives a workspace invitation.", category: "team", defaultTitle: "Workspace invitation", defaultMessage: () => "You were invited to join a workspace.", defaultPriority: "high", availableChannels: ["in_app","push","sound"], defaults: { push: true, sound: true }, allowedRecipientRoles: roles.everyone, requiredSection: "Team", navigationTarget: () => "/team", dedupeStrategy: "source_event", cooldownSeconds: 0, canBypassQuietHours: true, soundAllowed: true, sensitivePreviewAllowed: false }),
  "team.member_joined": event({ key: "team.member_joined", label: "Member joined", description: "A member joins the workspace.", category: "team", defaultTitle: "Team member joined", defaultMessage: () => "A team member joined the workspace.", defaultPriority: "normal", availableChannels: ["in_app","push"], allowedRecipientRoles: roles.managers, requiredSection: "Team", navigationTarget: () => "/team", dedupeStrategy: "source_event", cooldownSeconds: 0, canBypassQuietHours: false, soundAllowed: false, sensitivePreviewAllowed: false }),
  "team.member_removed": event({ key: "team.member_removed", label: "Member removed", description: "A member is removed or suspended.", category: "team", defaultTitle: "Team member removed", defaultMessage: () => "Workspace membership was removed.", defaultPriority: "high", availableChannels: ["in_app","push"], defaults: { push: true }, allowedRecipientRoles: roles.managers, requiredSection: "Team", navigationTarget: () => "/team", dedupeStrategy: "source_event", cooldownSeconds: 0, canBypassQuietHours: false, soundAllowed: false, sensitivePreviewAllowed: false }),
  "team.role_changed": event({ key: "team.role_changed", label: "Role changed", description: "A workspace member role changes.", category: "team", defaultTitle: "Team role changed", defaultMessage: () => "A team member role was updated.", defaultPriority: "normal", availableChannels: ["in_app","push"], allowedRecipientRoles: roles.managers, requiredSection: "Team", navigationTarget: () => "/team", dedupeStrategy: "source_event", cooldownSeconds: 0, canBypassQuietHours: false, soundAllowed: false, sensitivePreviewAllowed: false }),
  "finance.expense_created": event({ key: "finance.expense_created", label: "Expense created", description: "A workspace expense is recorded.", category: "finance", defaultTitle: "Expense recorded", defaultMessage: () => "A workspace expense was recorded.", defaultPriority: "normal", availableChannels: ["in_app","push"], allowedRecipientRoles: roles.managers, requiredSection: "Expenses", navigationTarget: () => "/expenses", dedupeStrategy: "source_event", cooldownSeconds: 0, canBypassQuietHours: false, soundAllowed: false, sensitivePreviewAllowed: false }),
  "ads.meta_sync_failed": event({ key: "ads.meta_sync_failed", label: "Meta sync failed", description: "Meta Ads synchronization fails.", category: "ads", defaultTitle: "Meta Ads sync failed", defaultMessage: () => "Meta Ads could not be synchronized.", defaultPriority: "high", availableChannels: ["in_app","push","sound"], defaults: { push: true, sound: true }, allowedRecipientRoles: roles.managers, requiredSection: "Ads Manager", navigationTarget: () => "/ads-manager", dedupeStrategy: "failure_window", cooldownSeconds: 900, canBypassQuietHours: false, soundAllowed: true, sensitivePreviewAllowed: false }),
  "ads.tiktok_sync_failed": event({ key: "ads.tiktok_sync_failed", label: "TikTok sync failed", description: "TikTok Ads synchronization fails.", category: "ads", defaultTitle: "TikTok Ads sync failed", defaultMessage: () => "TikTok Ads could not be synchronized.", defaultPriority: "high", availableChannels: ["in_app","push","sound"], defaults: { push: true, sound: true }, allowedRecipientRoles: roles.managers, requiredSection: "TikTok Ads", navigationTarget: () => "/tiktok-ads", dedupeStrategy: "failure_window", cooldownSeconds: 900, canBypassQuietHours: false, soundAllowed: true, sensitivePreviewAllowed: false }),
  "ads.token_expired": event({ key: "ads.token_expired", label: "Ads token expired", description: "An advertising authorization expires.", category: "ads", defaultTitle: "Advertising token expired", defaultMessage: () => "Reconnect the advertising integration.", defaultPriority: "critical", availableChannels: ["in_app","push","sound"], defaults: { push: true, sound: true }, allowedRecipientRoles: roles.managers, requiredSection: "Ads Manager", navigationTarget: () => "/settings?tab=integrations", dedupeStrategy: "entity", cooldownSeconds: 3600, canBypassQuietHours: true, soundAllowed: true, sensitivePreviewAllowed: false }),
  "integration.connected": event({ key: "integration.connected", label: "Integration connected", description: "A workspace integration is connected.", category: "integrations", defaultTitle: "Integration connected", defaultMessage: () => "A workspace integration was connected.", defaultPriority: "normal", availableChannels: ["in_app"], allowedRecipientRoles: roles.managers, requiredSection: "Settings", navigationTarget: () => "/settings?tab=integrations", dedupeStrategy: "source_event", cooldownSeconds: 0, canBypassQuietHours: false, soundAllowed: false, sensitivePreviewAllowed: false }),
  "integration.disconnected": event({ key: "integration.disconnected", label: "Integration disconnected", description: "A workspace integration disconnects.", category: "integrations", defaultTitle: "Integration disconnected", defaultMessage: () => "A workspace integration was disconnected.", defaultPriority: "high", availableChannels: ["in_app","push"], defaults: { push: true }, allowedRecipientRoles: roles.managers, requiredSection: "Settings", navigationTarget: () => "/settings?tab=integrations", dedupeStrategy: "source_event", cooldownSeconds: 0, canBypassQuietHours: false, soundAllowed: false, sensitivePreviewAllowed: false }),
  "integration.token_expired": event({ key: "integration.token_expired", label: "Integration token expired", description: "An integration needs renewed authorization.", category: "integrations", defaultTitle: "Integration authorization expired", defaultMessage: () => "Reconnect an integration to resume synchronization.", defaultPriority: "critical", availableChannels: ["in_app","push","sound"], defaults: { push: true, sound: true }, allowedRecipientRoles: roles.managers, requiredSection: "Settings", navigationTarget: () => "/settings?tab=integrations", dedupeStrategy: "entity", cooldownSeconds: 3600, canBypassQuietHours: true, soundAllowed: true, sensitivePreviewAllowed: false }),
  "integration.sync_failed": event({ key: "integration.sync_failed", label: "Integration sync failed", description: "A connected integration cannot synchronize.", category: "integrations", defaultTitle: "Integration sync failed", defaultMessage: () => "A workspace integration could not synchronize.", defaultPriority: "high", availableChannels: ["in_app","push"], defaults: { push: true }, allowedRecipientRoles: roles.managers, requiredSection: "Settings", navigationTarget: () => "/settings?tab=integrations", dedupeStrategy: "failure_window", cooldownSeconds: 900, canBypassQuietHours: false, soundAllowed: true, sensitivePreviewAllowed: false }),
  "security.new_login": event({ key: "security.new_login", label: "New login", description: "A new authenticated session is recorded.", category: "security", defaultTitle: "New login", defaultMessage: () => "A new login to Ecom OS was detected.", defaultPriority: "high", availableChannels: ["in_app","push"], defaults: { push: true }, allowedRecipientRoles: roles.everyone, requiredSection: null, navigationTarget: () => "/settings?tab=profile", dedupeStrategy: "source_event", cooldownSeconds: 0, canBypassQuietHours: true, soundAllowed: false, sensitivePreviewAllowed: false }),
  "security.password_changed": event({ key: "security.password_changed", label: "Password changed", description: "The account password changes.", category: "security", defaultTitle: "Password changed", defaultMessage: () => "Your Ecom OS password was changed.", defaultPriority: "critical", availableChannels: ["in_app","push","sound"], defaults: { push: true, sound: true }, allowedRecipientRoles: roles.everyone, requiredSection: null, navigationTarget: () => "/settings?tab=profile", dedupeStrategy: "source_event", cooldownSeconds: 0, canBypassQuietHours: true, soundAllowed: true, sensitivePreviewAllowed: false }),
  "security.integration_revoked": event({ key: "security.integration_revoked", label: "Integration revoked", description: "External integration access is revoked.", category: "security", defaultTitle: "Integration access revoked", defaultMessage: () => "An integration authorization was revoked.", defaultPriority: "critical", availableChannels: ["in_app","push","sound"], defaults: { push: true, sound: true }, allowedRecipientRoles: roles.managers, requiredSection: null, navigationTarget: () => "/settings?tab=integrations", dedupeStrategy: "source_event", cooldownSeconds: 0, canBypassQuietHours: true, soundAllowed: true, sensitivePreviewAllowed: false }),
  "system.announcement": event({ key: "system.announcement", label: "Announcement", description: "An authorized platform announcement is published.", category: "system", defaultTitle: "Ecom OS announcement", defaultMessage: () => "There is a new Ecom OS announcement.", defaultPriority: "normal", availableChannels: ["in_app","push"], defaults: { push: true }, allowedRecipientRoles: roles.everyone, requiredSection: null, navigationTarget: () => "/notifications", dedupeStrategy: "source_event", cooldownSeconds: 0, canBypassQuietHours: false, soundAllowed: true, sensitivePreviewAllowed: false }),
  "system.maintenance": event({ key: "system.maintenance", label: "Maintenance", description: "Scheduled Ecom OS maintenance is announced.", category: "system", defaultTitle: "Scheduled maintenance", defaultMessage: () => "Ecom OS maintenance is scheduled.", defaultPriority: "high", availableChannels: ["in_app","push"], defaults: { push: true }, allowedRecipientRoles: roles.everyone, requiredSection: null, navigationTarget: () => "/notifications", dedupeStrategy: "source_event", cooldownSeconds: 0, canBypassQuietHours: true, soundAllowed: false, sensitivePreviewAllowed: false }),
  "system.incident": event({ key: "system.incident", label: "Service incident", description: "A critical Ecom OS incident is announced.", category: "system", defaultTitle: "Service incident", defaultMessage: () => "An Ecom OS service incident needs attention.", defaultPriority: "critical", availableChannels: ["in_app","push","sound"], defaults: { push: true, sound: true }, allowedRecipientRoles: roles.everyone, requiredSection: null, navigationTarget: () => "/notifications", dedupeStrategy: "source_event", cooldownSeconds: 0, canBypassQuietHours: true, soundAllowed: true, sensitivePreviewAllowed: false }),
  "system.feature_update": event({ key: "system.feature_update", label: "Feature update", description: "A new Ecom OS feature is announced.", category: "system", defaultTitle: "New Ecom OS feature", defaultMessage: () => "A new Ecom OS feature is available.", defaultPriority: "normal", availableChannels: ["in_app","push"], allowedRecipientRoles: roles.everyone, requiredSection: null, navigationTarget: () => "/notifications", dedupeStrategy: "source_event", cooldownSeconds: 0, canBypassQuietHours: false, soundAllowed: true, sensitivePreviewAllowed: false }),
} as const satisfies Record<string, NotificationEventDefinition>;

export type NotificationEventKey = keyof typeof NOTIFICATION_EVENTS;

export const NOTIFICATION_EVENT_LIST = Object.values(NOTIFICATION_EVENTS);

export function isNotificationEventKey(value: string): value is NotificationEventKey {
  return Object.prototype.hasOwnProperty.call(NOTIFICATION_EVENTS, value);
}
