-- Privacy-safe realtime projection for the Live View.
-- Raw customer IP addresses remain exclusively on public.orders.

create table if not exists public.live_view_city_catalog (
  id bigint generated by default as identity primary key,
  canonical_name text not null,
  country_code text not null check (char_length(country_code) = 2),
  country_name text not null,
  region text,
  latitude double precision not null check (latitude between -90 and 90),
  longitude double precision not null check (longitude between -180 and 180),
  source text not null default 'geonames',
  created_at timestamptz not null default now(),
  unique (canonical_name, country_code)
);

create table if not exists public.live_view_city_aliases (
  id bigint generated by default as identity primary key,
  city_id bigint not null references public.live_view_city_catalog(id) on delete cascade,
  workspace_id uuid references public.workspaces(id) on delete cascade,
  alias text not null,
  normalized_alias text generated always as (
    lower(regexp_replace(btrim(alias), '[^[:alnum:]]+', '', 'g'))
  ) stored,
  created_at timestamptz not null default now()
);

create unique index if not exists live_view_city_aliases_global_uq
  on public.live_view_city_aliases (normalized_alias)
  where workspace_id is null;
create unique index if not exists live_view_city_aliases_workspace_uq
  on public.live_view_city_aliases (workspace_id, normalized_alias)
  where workspace_id is not null;
create index if not exists live_view_city_aliases_city_idx
  on public.live_view_city_aliases (city_id);

create table if not exists public.live_view_geo_cache (
  ip_hash text primary key check (char_length(ip_hash) = 64),
  city text,
  region text,
  country text,
  country_code text,
  latitude double precision check (latitude between -90 and 90),
  longitude double precision check (longitude between -180 and 180),
  provider text not null,
  confidence text not null check (confidence in ('high', 'medium', 'low')),
  resolved_at timestamptz not null default now(),
  expires_at timestamptz not null
);
create index if not exists live_view_geo_cache_expiry_idx
  on public.live_view_geo_cache (expires_at);

create table if not exists public.live_view_events (
  order_id uuid primary key references public.orders("Order ID") on delete cascade,
  workspace_id uuid not null references public.workspaces(id) on delete cascade,
  occurred_at timestamptz not null,
  status text not null,
  total numeric not null default 0,
  currency text,
  source text,
  product_name text,
  campaign text,
  city text,
  region text,
  country text,
  country_code text,
  latitude double precision check (latitude between -90 and 90),
  longitude double precision check (longitude between -180 and 180),
  geo_source text not null default 'unknown'
    check (geo_source in ('ip', 'city', 'provider_city', 'region', 'country', 'unknown')),
  geo_confidence text not null default 'low'
    check (geo_confidence in ('high', 'medium', 'low')),
  updated_at timestamptz not null default now()
);

create index if not exists live_view_events_workspace_time_idx
  on public.live_view_events (workspace_id, occurred_at desc);
create index if not exists live_view_events_time_idx
  on public.live_view_events (occurred_at desc);
create index if not exists live_view_events_workspace_city_idx
  on public.live_view_events (workspace_id, city, occurred_at desc);

alter table public.live_view_city_catalog enable row level security;
alter table public.live_view_city_aliases enable row level security;
alter table public.live_view_geo_cache enable row level security;
alter table public.live_view_events enable row level security;

drop policy if exists live_view_catalog_read on public.live_view_city_catalog;
create policy live_view_catalog_read on public.live_view_city_catalog
  for select to authenticated using (true);

drop policy if exists live_view_aliases_read on public.live_view_city_aliases;
create policy live_view_aliases_read on public.live_view_city_aliases
  for select to authenticated using (
    workspace_id is null
    or (select public.is_active_workspace_member(workspace_id))
    or (select public.has_platform_permission('orders.read_all'))
  );

drop policy if exists live_view_events_read on public.live_view_events;
create policy live_view_events_read on public.live_view_events
  for select to authenticated using (
    (select public.is_active_workspace_member(workspace_id))
    or (select public.has_platform_permission('orders.read_all'))
  );

revoke all on table public.live_view_geo_cache from anon, authenticated;
revoke all on table public.live_view_city_catalog from anon;
revoke all on table public.live_view_city_aliases from anon;
revoke all on table public.live_view_events from anon;
grant select on public.live_view_city_catalog, public.live_view_city_aliases, public.live_view_events to authenticated;

insert into public.live_view_city_catalog
  (canonical_name, country_code, country_name, region, latitude, longitude)
values
  ('Casablanca','MA','Morocco','Casablanca-Settat',33.5731,-7.5898),
  ('Marrakech','MA','Morocco','Marrakech-Safi',31.6295,-7.9811),
  ('Rabat','MA','Morocco','Rabat-Sale-Kenitra',34.0209,-6.8416),
  ('Fes','MA','Morocco','Fes-Meknes',34.0181,-5.0078),
  ('Tangier','MA','Morocco','Tanger-Tetouan-Al Hoceima',35.7595,-5.8340),
  ('Agadir','MA','Morocco','Souss-Massa',30.4278,-9.5981),
  ('Meknes','MA','Morocco','Fes-Meknes',33.8935,-5.5473),
  ('Oujda','MA','Morocco','Oriental',34.6814,-1.9086),
  ('Kenitra','MA','Morocco','Rabat-Sale-Kenitra',34.2610,-6.5802),
  ('Tetouan','MA','Morocco','Tanger-Tetouan-Al Hoceima',35.5889,-5.3626),
  ('Safi','MA','Morocco','Marrakech-Safi',32.2994,-9.2372),
  ('El Jadida','MA','Morocco','Casablanca-Settat',33.2316,-8.5007),
  ('Nador','MA','Morocco','Oriental',35.1681,-2.9335),
  ('Beni Mellal','MA','Morocco','Beni Mellal-Khenifra',32.3373,-6.3498),
  ('Mohammedia','MA','Morocco','Casablanca-Settat',33.6861,-7.3830),
  ('Sale','MA','Morocco','Rabat-Sale-Kenitra',34.0531,-6.7985),
  ('Paris','FR','France','Ile-de-France',48.8566,2.3522),
  ('Madrid','ES','Spain','Community of Madrid',40.4168,-3.7038),
  ('London','GB','United Kingdom','England',51.5074,-0.1278),
  ('New York','US','United States','New York',40.7128,-74.0060),
  ('Dubai','AE','United Arab Emirates','Dubai',25.2048,55.2708),
  ('Riyadh','SA','Saudi Arabia','Riyadh',24.7136,46.6753),
  ('Cairo','EG','Egypt','Cairo',30.0444,31.2357),
  ('Istanbul','TR','Turkey','Istanbul',41.0082,28.9784)
on conflict (canonical_name, country_code) do update set
  region = excluded.region,
  latitude = excluded.latitude,
  longitude = excluded.longitude;

with aliases(canonical_name, country_code, alias) as (
  values
    ('Casablanca','MA','Casablanca'),('Casablanca','MA','Casa'),('Casablanca','MA','الدار البيضاء'),
    ('Marrakech','MA','Marrakech'),('Marrakech','MA','Marrakesh'),('Marrakech','MA','مراكش'),
    ('Rabat','MA','Rabat'),('Rabat','MA','الرباط'),
    ('Fes','MA','Fes'),('Fes','MA','Fez'),('Fes','MA','فاس'),
    ('Tangier','MA','Tangier'),('Tangier','MA','Tanger'),('Tangier','MA','طنجة'),
    ('Agadir','MA','Agadir'),('Agadir','MA','أكادير'),
    ('Meknes','MA','Meknes'),('Meknes','MA','مكناس'),
    ('Oujda','MA','Oujda'),('Oujda','MA','وجدة'),
    ('Kenitra','MA','Kenitra'),('Kenitra','MA','Kénitra'),('Kenitra','MA','القنيطرة'),
    ('Tetouan','MA','Tetouan'),('Tetouan','MA','Tétouan'),('Tetouan','MA','تطوان'),
    ('Safi','MA','Safi'),('Safi','MA','آسفي'),
    ('El Jadida','MA','El Jadida'),('El Jadida','MA','الجديدة'),
    ('Nador','MA','Nador'),('Nador','MA','الناظور'),
    ('Beni Mellal','MA','Beni Mellal'),('Beni Mellal','MA','Béni Mellal'),('Beni Mellal','MA','بني ملال'),
    ('Mohammedia','MA','Mohammedia'),('Mohammedia','MA','المحمدية'),
    ('Sale','MA','Sale'),('Sale','MA','Salé'),('Sale','MA','سلا'),
    ('Paris','FR','Paris'),('Madrid','ES','Madrid'),('London','GB','London'),
    ('New York','US','New York'),('Dubai','AE','Dubai'),('Riyadh','SA','Riyadh'),
    ('Cairo','EG','Cairo'),('Istanbul','TR','Istanbul')
)
insert into public.live_view_city_aliases(city_id, alias)
select c.id, a.alias from aliases a
join public.live_view_city_catalog c using (canonical_name, country_code)
on conflict do nothing;

create or replace function public.resolve_live_view_city_v1(
  p_workspace_id uuid,
  p_city text,
  p_country text default null
)
returns table (
  city text, region text, country text, country_code text,
  latitude double precision, longitude double precision,
  geo_source text, geo_confidence text
)
language sql stable security definer set search_path = ''
as $function$
  with input as (
    select lower(regexp_replace(btrim(coalesce(p_city,'')), '[^[:alnum:]]+', '', 'g')) n,
           upper(btrim(coalesce(p_country,''))) c
  ), mapped as (
    select catalog.*, alias.workspace_id
    from public.live_view_city_aliases alias
    join public.live_view_city_catalog catalog on catalog.id = alias.city_id
    cross join input
    where alias.normalized_alias = input.n
      and (alias.workspace_id = p_workspace_id or alias.workspace_id is null)
      and (input.c = '' or input.c in (catalog.country_code, upper(catalog.country_name)))
    order by (alias.workspace_id is not null) desc
    limit 1
  )
  select mapped.canonical_name, mapped.region, mapped.country_name, mapped.country_code,
         mapped.latitude, mapped.longitude,
         case when mapped.workspace_id is null then 'city' else 'provider_city' end,
         'medium'
  from mapped
$function$;
revoke all on function public.resolve_live_view_city_v1(uuid,text,text) from public;
grant execute on function public.resolve_live_view_city_v1(uuid,text,text) to service_role;

create or replace function public.project_live_view_order_v1()
returns trigger language plpgsql security definer set search_path = ''
as $function$
declare resolved record;
begin
  select * into resolved
  from public.resolve_live_view_city_v1(new.workspace_id, coalesce(new.city,new.raw_city), new.country)
  limit 1;

  insert into public.live_view_events (
    order_id, workspace_id, occurred_at, status, total, currency, source,
    product_name, campaign, city, region, country, country_code,
    latitude, longitude, geo_source, geo_confidence, updated_at
  ) values (
    new."Order ID", new.workspace_id, coalesce(new.order_date,new.created_at),
    coalesce(new.status,'unknown'), coalesce(new.total,0), new.currency,
    coalesce(new.source_platform,new.source,new.utm_source), new.product_name,
    new.utm_campaign, coalesce(resolved.city,new.city,new.raw_city),
    coalesce(resolved.region,new.region), coalesce(resolved.country,new.country),
    resolved.country_code, resolved.latitude, resolved.longitude,
    coalesce(resolved.geo_source,case when nullif(btrim(new.country),'') is not null then 'country' else 'unknown' end),
    coalesce(resolved.geo_confidence,'low'), now()
  )
  on conflict (order_id) do update set
    workspace_id=excluded.workspace_id, occurred_at=excluded.occurred_at,
    status=excluded.status, total=excluded.total, currency=excluded.currency,
    source=excluded.source, product_name=excluded.product_name,
    campaign=excluded.campaign,
    city=case when public.live_view_events.geo_source='ip' then public.live_view_events.city else excluded.city end,
    region=case when public.live_view_events.geo_source='ip' then public.live_view_events.region else excluded.region end,
    country=case when public.live_view_events.geo_source='ip' then public.live_view_events.country else excluded.country end,
    country_code=case when public.live_view_events.geo_source='ip' then public.live_view_events.country_code else excluded.country_code end,
    latitude=case when public.live_view_events.geo_source='ip' then public.live_view_events.latitude else excluded.latitude end,
    longitude=case when public.live_view_events.geo_source='ip' then public.live_view_events.longitude else excluded.longitude end,
    geo_source=case when public.live_view_events.geo_source='ip' then 'ip' else excluded.geo_source end,
    geo_confidence=case when public.live_view_events.geo_source='ip' then public.live_view_events.geo_confidence else excluded.geo_confidence end,
    updated_at=now();
  return new;
end
$function$;

drop trigger if exists orders_live_view_projection on public.orders;
create trigger orders_live_view_projection
after insert or update of status,total,currency,source,source_platform,product_name,utm_campaign,city,raw_city,region,country,order_date
on public.orders for each row execute function public.project_live_view_order_v1();

insert into public.live_view_events (
  order_id, workspace_id, occurred_at, status, total, currency, source,
  product_name, campaign, city, region, country, country_code,
  latitude, longitude, geo_source, geo_confidence
)
select o."Order ID",o.workspace_id,coalesce(o.order_date,o.created_at),o.status,
       coalesce(o.total,0),o.currency,coalesce(o.source_platform,o.source,o.utm_source),
       o.product_name,o.utm_campaign,coalesce(r.city,o.city,o.raw_city),
       coalesce(r.region,o.region),coalesce(r.country,o.country),r.country_code,
       r.latitude,r.longitude,
       coalesce(r.geo_source,case when nullif(btrim(o.country),'') is not null then 'country' else 'unknown' end),
       coalesce(r.geo_confidence,'low')
from public.orders o
left join lateral public.resolve_live_view_city_v1(o.workspace_id,coalesce(o.city,o.raw_city),o.country) r on true
on conflict (order_id) do nothing;

create or replace function public.get_live_view_snapshot_v1(
  p_workspace_id uuid,
  p_window text default '15m',
  p_filters jsonb default '{}'::jsonb,
  p_admin_global boolean default false
)
returns jsonb language plpgsql stable security definer set search_path = ''
as $function$
declare since_at timestamptz; result jsonb;
begin
  if (select auth.uid()) is null then raise exception 'Authentication required'; end if;
  if p_admin_global then
    if not public.has_platform_permission('orders.read_all') then raise exception 'Access denied'; end if;
  elsif p_workspace_id is null or not public.is_active_workspace_member(p_workspace_id) then
    raise exception 'Access denied';
  end if;

  since_at := case lower(coalesce(p_window,'15m'))
    when 'live' then now() - interval '2 minutes'
    when '1m' then now() - interval '1 minute'
    when '5m' then now() - interval '5 minutes'
    when '15m' then now() - interval '15 minutes'
    when '1h' then now() - interval '1 hour'
    when 'today' then date_trunc('day',now())
    else now() - interval '15 minutes' end;

  with filtered as (
    select e.*, w.name workspace_name
    from public.live_view_events e
    join public.workspaces w on w.id=e.workspace_id
    where e.occurred_at >= since_at
      and (p_admin_global or e.workspace_id=p_workspace_id)
      and (nullif(p_filters->>'status','') is null or lower(e.status)=lower(p_filters->>'status'))
      and (nullif(p_filters->>'source','') is null or lower(coalesce(e.source,''))=lower(p_filters->>'source'))
      and (nullif(p_filters->>'product','') is null or lower(coalesce(e.product_name,''))=lower(p_filters->>'product'))
      and (nullif(p_filters->>'city','') is null or lower(coalesce(e.city,''))=lower(p_filters->>'city'))
      and (nullif(p_filters->>'campaign','') is null or lower(coalesce(e.campaign,''))=lower(p_filters->>'campaign'))
      and (nullif(p_filters->>'country','') is null or lower(coalesce(e.country,''))=lower(p_filters->>'country'))
      and (nullif(p_filters->>'workspace_id','') is null or e.workspace_id::text=p_filters->>'workspace_id')
  ), recent as (
    select * from filtered order by occurred_at desc limit 200
  ), option_source as (
    select jsonb_build_object(
      'statuses',coalesce((select jsonb_agg(x) from (select distinct status x from filtered where status is not null order by 1) q),'[]'::jsonb),
      'sources',coalesce((select jsonb_agg(x) from (select distinct source x from filtered where source is not null order by 1) q),'[]'::jsonb),
      'products',coalesce((select jsonb_agg(x) from (select distinct product_name x from filtered where product_name is not null order by 1) q),'[]'::jsonb),
      'cities',coalesce((select jsonb_agg(x) from (select distinct city x from filtered where city is not null order by 1) q),'[]'::jsonb),
      'campaigns',coalesce((select jsonb_agg(x) from (select distinct campaign x from filtered where campaign is not null order by 1) q),'[]'::jsonb),
      'countries',coalesce((select jsonb_agg(x) from (select distinct country x from filtered where country is not null order by 1) q),'[]'::jsonb),
      'workspaces',coalesce((select jsonb_agg(jsonb_build_object('id',workspace_id,'name',workspace_name)) from (select distinct workspace_id,workspace_name from filtered order by workspace_name) q),'[]'::jsonb)
    ) options
  )
  select jsonb_build_object(
    'generated_at',now(),
    'orders',coalesce((select count(*) from filtered),0),
    'revenue_by_currency',coalesce((select jsonb_object_agg(currency,total) from (select coalesce(currency,'—') currency,sum(total) total from filtered group by 1) q),'{}'::jsonb),
    'events',coalesce((select jsonb_agg(jsonb_build_object(
      'order_id',order_id,'workspace_id',workspace_id,'workspace_name',workspace_name,
      'occurred_at',occurred_at,'status',status,'total',total,'currency',currency,
      'source',source,'product_name',product_name,'campaign',campaign,'city',city,
      'region',region,'country',country,'country_code',country_code,
      'latitude',latitude,'longitude',longitude,'geo_source',geo_source,'geo_confidence',geo_confidence
    ) order by occurred_at desc) from recent),'[]'::jsonb),
    'top_cities',coalesce((select jsonb_agg(to_jsonb(q)) from (select coalesce(city,'Unknown') label,count(*) orders,sum(total) revenue from filtered group by 1 order by orders desc limit 8) q),'[]'::jsonb),
    'top_products',coalesce((select jsonb_agg(to_jsonb(q)) from (select coalesce(product_name,'Unknown') label,count(*) orders,sum(total) revenue from filtered group by 1 order by orders desc limit 8) q),'[]'::jsonb),
    'top_sources',coalesce((select jsonb_agg(to_jsonb(q)) from (select coalesce(source,'Unknown') label,count(*) orders,sum(total) revenue from filtered group by 1 order by orders desc limit 8) q),'[]'::jsonb),
    'top_campaigns',coalesce((select jsonb_agg(to_jsonb(q)) from (select coalesce(campaign,'Unattributed') label,count(*) orders,sum(total) revenue from filtered group by 1 order by orders desc limit 8) q),'[]'::jsonb),
    'top_workspaces',case when p_admin_global then coalesce((select jsonb_agg(to_jsonb(q)) from (select workspace_id,workspace_name label,count(*) orders,sum(total) revenue from filtered group by 1,2 order by orders desc limit 8) q),'[]'::jsonb) else '[]'::jsonb end,
    'options',(select options from option_source)
  ) into result;
  return result;
end
$function$;

revoke all on function public.get_live_view_snapshot_v1(uuid,text,jsonb,boolean) from public;
grant execute on function public.get_live_view_snapshot_v1(uuid,text,jsonb,boolean) to authenticated;

do $block$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname='supabase_realtime' and schemaname='public' and tablename='live_view_events'
  ) then
    alter publication supabase_realtime add table public.live_view_events;
  end if;
end
$block$;

comment on table public.live_view_events is 'Privacy-safe realtime order activity projection; contains no customer PII or IP.';
comment on table public.live_view_geo_cache is 'Server-only hashed IP geolocation cache; never stores raw IP addresses.';
