create table if not exists public.live_view_region_catalog (
  id bigint generated by default as identity primary key,
  region_name text not null,
  country_code text not null check (char_length(country_code)=2),
  latitude double precision not null check (latitude between -90 and 90),
  longitude double precision not null check (longitude between -180 and 180),
  unique(region_name,country_code)
);
create table if not exists public.live_view_country_catalog (
  country_code text primary key check (char_length(country_code)=2),
  country_name text not null unique,
  latitude double precision not null check (latitude between -90 and 90),
  longitude double precision not null check (longitude between -180 and 180)
);
alter table public.live_view_region_catalog enable row level security;
alter table public.live_view_country_catalog enable row level security;
revoke all on public.live_view_region_catalog, public.live_view_country_catalog from public,anon,authenticated;

insert into public.live_view_region_catalog(region_name,country_code,latitude,longitude) values
 ('Tanger-Tetouan-Al Hoceima','MA',35.20,-5.30),('Oriental','MA',34.68,-1.91),
 ('Fes-Meknes','MA',34.02,-5.01),('Rabat-Sale-Kenitra','MA',34.02,-6.84),
 ('Beni Mellal-Khenifra','MA',32.34,-6.35),('Casablanca-Settat','MA',33.30,-7.60),
 ('Marrakech-Safi','MA',31.63,-7.98),('Draa-Tafilalet','MA',31.93,-4.42),
 ('Souss-Massa','MA',30.43,-9.60),('Guelmim-Oued Noun','MA',28.99,-10.06),
 ('Laayoune-Sakia El Hamra','MA',27.15,-13.20),('Dakhla-Oued Ed-Dahab','MA',23.68,-15.96)
on conflict(region_name,country_code) do update set latitude=excluded.latitude,longitude=excluded.longitude;

insert into public.live_view_country_catalog(country_code,country_name,latitude,longitude) values
 ('MA','Morocco',31.7917,-7.0926),('FR','France',46.2276,2.2137),
 ('ES','Spain',40.4637,-3.7492),('GB','United Kingdom',55.3781,-3.4360),
 ('US','United States',37.0902,-95.7129),('AE','United Arab Emirates',23.4241,53.8478),
 ('SA','Saudi Arabia',23.8859,45.0792),('EG','Egypt',26.8206,30.8025),
 ('TR','Turkey',38.9637,35.2433)
on conflict(country_code) do update set country_name=excluded.country_name,latitude=excluded.latitude,longitude=excluded.longitude;

create or replace function public.resolve_live_view_location_v1(
 p_workspace_id uuid,p_city text,p_region text,p_country text
) returns table(city text,region text,country text,country_code text,latitude double precision,longitude double precision,geo_source text,geo_confidence text)
language plpgsql stable security definer set search_path=''
as $function$
declare ncity text:=lower(regexp_replace(btrim(coalesce(p_city,'')),'[^[:alnum:]]+','','g'));
declare nregion text:=lower(regexp_replace(btrim(coalesce(p_region,'')),'[^[:alnum:]]+','','g'));
declare ncountry text:=lower(regexp_replace(btrim(coalesce(p_country,'')),'[^[:alnum:]]+','','g'));
begin
 return query
 select c.canonical_name,c.region,c.country_name,c.country_code,c.latitude,c.longitude,
   case when a.workspace_id is not null or exists(select 1 from public.shipping_city_mapping s where s.workspace_id=p_workspace_id and lower(regexp_replace(btrim(s.city_name),'[^[:alnum:]]+','','g'))=ncity) then 'provider_city' else 'city' end,
   'medium'::text
 from public.live_view_city_aliases a join public.live_view_city_catalog c on c.id=a.city_id
 where a.normalized_alias=ncity and (a.workspace_id=p_workspace_id or a.workspace_id is null)
   and (ncountry='' or ncountry in (lower(c.country_code),lower(c.country_name)))
 order by (a.workspace_id is not null) desc limit 1;
 if found then return; end if;

 return query select p_city,r.region_name,c.country_name,r.country_code,r.latitude,r.longitude,'region'::text,'low'::text
 from public.live_view_region_catalog r join public.live_view_country_catalog c using(country_code)
 where lower(regexp_replace(btrim(r.region_name),'[^[:alnum:]]+','','g'))=nregion
   and (ncountry='' or ncountry in (lower(c.country_code),lower(c.country_name))) limit 1;
 if found then return; end if;

 return query select p_city,p_region,c.country_name,c.country_code,c.latitude,c.longitude,'country'::text,'low'::text
 from public.live_view_country_catalog c
 where ncountry in (lower(c.country_code),lower(c.country_name)) limit 1;
end
$function$;
revoke execute on function public.resolve_live_view_location_v1(uuid,text,text,text) from public,anon,authenticated;
grant execute on function public.resolve_live_view_location_v1(uuid,text,text,text) to service_role;

create or replace function public.project_live_view_order_v1()
returns trigger language plpgsql security definer set search_path=''
as $function$
declare resolved record;
begin
 select * into resolved from public.resolve_live_view_location_v1(new.workspace_id,coalesce(new.city,new.raw_city),new.region,new.country) limit 1;
 insert into public.live_view_events(order_id,workspace_id,occurred_at,status,total,currency,source,product_name,campaign,city,region,country,country_code,latitude,longitude,geo_source,geo_confidence,updated_at)
 values(new."Order ID",new.workspace_id,coalesce(new.order_date,new.created_at),coalesce(new.status,'unknown'),coalesce(new.total,0),new.currency,coalesce(new.source_platform,new.source,new.utm_source),new.product_name,new.utm_campaign,coalesce(resolved.city,new.city,new.raw_city),coalesce(resolved.region,new.region),coalesce(resolved.country,new.country),resolved.country_code,resolved.latitude,resolved.longitude,coalesce(resolved.geo_source,'unknown'),coalesce(resolved.geo_confidence,'low'),now())
 on conflict(order_id) do update set workspace_id=excluded.workspace_id,occurred_at=excluded.occurred_at,status=excluded.status,total=excluded.total,currency=excluded.currency,source=excluded.source,product_name=excluded.product_name,campaign=excluded.campaign,
 city=case when public.live_view_events.geo_source='ip' then public.live_view_events.city else excluded.city end,
 region=case when public.live_view_events.geo_source='ip' then public.live_view_events.region else excluded.region end,
 country=case when public.live_view_events.geo_source='ip' then public.live_view_events.country else excluded.country end,
 country_code=case when public.live_view_events.geo_source='ip' then public.live_view_events.country_code else excluded.country_code end,
 latitude=case when public.live_view_events.geo_source='ip' then public.live_view_events.latitude else excluded.latitude end,
 longitude=case when public.live_view_events.geo_source='ip' then public.live_view_events.longitude else excluded.longitude end,
 geo_source=case when public.live_view_events.geo_source='ip' then 'ip' else excluded.geo_source end,
 geo_confidence=case when public.live_view_events.geo_source='ip' then public.live_view_events.geo_confidence else excluded.geo_confidence end,updated_at=now();
 return new;
end
$function$;
revoke execute on function public.project_live_view_order_v1() from public,anon,authenticated;

with resolved as (
 select e.order_id,r.* from public.live_view_events e
 left join lateral public.resolve_live_view_location_v1(e.workspace_id,e.city,e.region,e.country) r on true
 where e.geo_source<>'ip'
)
update public.live_view_events e set city=coalesce(r.city,e.city),region=coalesce(r.region,e.region),country=coalesce(r.country,e.country),country_code=r.country_code,latitude=r.latitude,longitude=r.longitude,geo_source=coalesce(r.geo_source,'unknown'),geo_confidence=coalesce(r.geo_confidence,'low'),updated_at=now()
from resolved r where e.order_id=r.order_id;
