import { useCallback, useEffect, useState } from "react";
import { AlertTriangle, RefreshCw, X } from "lucide-react";
import { supabase } from "../../lib/supabase";
import { PageHeader } from "../../components/PageHeader";

type ErrorRow = { id: string; error_id: string; severity: string; module: string; action: string | null; workspace_id: string | null; user_id: string | null; error_code: string; safe_message: string; metadata: Record<string, unknown>; occurrence_count: number; first_seen_at: string; last_seen_at: string; resolved_status: string };

export default function ErrorCenter() {
  const [rows, setRows] = useState<ErrorRow[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [status, setStatus] = useState(""); const [severity, setSeverity] = useState(""); const [search, setSearch] = useState(""); const [selected, setSelected] = useState<ErrorRow | null>(null);
  const load = useCallback(async () => { setLoading(true); setError(null); let query = supabase.from("ecom_error_events").select("*").order("last_seen_at", { ascending: false }).range(0, 99); if (status) query = query.eq("resolved_status", status); if (severity) query = query.eq("severity", severity); if (search) query = query.or(`error_id.ilike.%${search}%,error_code.ilike.%${search}%,module.ilike.%${search}%`); const result = await query; if (result.error) setError("We couldn't load the Error Center. Try again."); else setRows((result.data || []) as ErrorRow[]); setLoading(false); }, [search, severity, status]);
  useEffect(() => { void load(); }, [load]);
  const updateStatus = async (row: ErrorRow, value: string) => { const result = await supabase.from("ecom_error_events").update({ resolved_status: value }).eq("id", row.id); if (result.error) return; setRows((current) => current.map((item) => item.id === row.id ? { ...item, resolved_status: value } : item)); setSelected((current) => current ? { ...current, resolved_status: value } : null); };
  return <div className="mx-auto max-w-7xl p-4 md:p-6"><PageHeader title="Error Center" subtitle="Safe, actionable platform failures and support references." action={<button onClick={() => void load()} className="inline-flex items-center gap-2 rounded-xl border border-base-border px-3 py-2 text-xs font-semibold"><RefreshCw size={14} /> Refresh</button>} />
    <div className="mb-4 flex flex-wrap gap-2"><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search error ID, code or module" className="min-w-64 flex-1 rounded-xl border border-base-border bg-base-surface px-3 py-2 text-sm" /><select value={severity} onChange={(e) => setSeverity(e.target.value)} className="rounded-xl border border-base-border bg-base-surface px-3 py-2 text-sm"><option value="">All severities</option><option>warning</option><option>error</option><option>critical</option></select><select value={status} onChange={(e) => setStatus(e.target.value)} className="rounded-xl border border-base-border bg-base-surface px-3 py-2 text-sm"><option value="">All statuses</option><option value="open">Open</option><option value="investigating">Investigating</option><option value="resolved">Resolved</option><option value="ignored">Ignored</option></select></div>
    {error && <div className="mb-4 rounded-xl border border-danger/20 bg-danger/5 p-3 text-sm text-danger">{error}</div>}
    <div className="overflow-x-auto rounded-2xl border border-base-border bg-base-surface"><table className="w-full min-w-[900px] text-left text-xs"><thead className="bg-base-raised text-[10px] uppercase text-ink-muted"><tr>{["Error ID","Severity","Module / action","Code","Workspace","Occurrences","Last seen","Status"].map((h) => <th key={h} className="px-4 py-3">{h}</th>)}</tr></thead><tbody>{loading ? <tr><td colSpan={8} className="p-10 text-center text-ink-muted">Loading errors…</td></tr> : rows.length === 0 ? <tr><td colSpan={8} className="p-10 text-center text-ink-muted">No errors recorded.</td></tr> : rows.map((row) => <tr key={row.id} onClick={() => setSelected(row)} className="cursor-pointer border-t border-base-border hover:bg-base-raised/60"><td className="px-4 py-3 font-mono font-semibold">{row.error_id}</td><td className="px-4 py-3"><span className="rounded-full bg-base-raised px-2 py-1">{row.severity}</span></td><td className="px-4 py-3">{row.module}{row.action ? ` · ${row.action}` : ""}</td><td className="px-4 py-3 font-mono">{row.error_code}</td><td className="px-4 py-3 font-mono">{row.workspace_id || "—"}</td><td className="px-4 py-3">{row.occurrence_count}</td><td className="px-4 py-3">{new Date(row.last_seen_at).toLocaleString()}</td><td className="px-4 py-3">{row.resolved_status}</td></tr>)}</tbody></table></div>
    {selected && <aside className="fixed inset-y-0 right-0 z-50 w-full max-w-lg overflow-y-auto border-l border-base-border bg-base-surface p-5 shadow-2xl"><button onClick={() => setSelected(null)} className="float-right rounded-lg p-2 hover:bg-base-raised"><X size={18} /></button><AlertTriangle className="text-danger" /><h2 className="mt-3 text-xl font-bold">{selected.error_id}</h2><p className="mt-2 text-sm text-ink-muted">{selected.safe_message}</p><dl className="mt-6 space-y-3 text-sm">{([["Code", selected.error_code],["Module", selected.module],["Action", selected.action || "—"],["Workspace", selected.workspace_id || "—"],["User", selected.user_id || "—"],["Occurrences", selected.occurrence_count],["First seen", new Date(selected.first_seen_at).toLocaleString()],["Last seen", new Date(selected.last_seen_at).toLocaleString()]] as const).map(([label, value]) => <div key={label} className="flex justify-between gap-4 border-b border-base-border pb-2"><dt className="text-ink-muted">{label}</dt><dd className="text-right font-medium">{String(value)}</dd></div>)}</dl><label className="mt-6 block text-sm font-semibold">Resolution status<select value={selected.resolved_status} onChange={(e) => void updateStatus(selected, e.target.value)} className="mt-2 w-full rounded-xl border border-base-border bg-base-surface px-3 py-2.5"><option value="open">Open</option><option value="investigating">Investigating</option><option value="resolved">Resolved</option><option value="ignored">Ignored</option></select></label><pre className="mt-6 overflow-auto rounded-xl bg-base-raised p-3 text-[11px]">{JSON.stringify(selected.metadata || {}, null, 2)}</pre></aside>}
  </div>;
}
